apiVersion: couchbase.database.couchbase.com/v1beta1
kind: CouchbaseCluster
metadata:
  name: cb-example-aks-CUSTOMER_NAME
spec:
  baseImage: couchbase/server
  version: enterprise-5.0.1
  authSecret: cb-example-auth
  exposeAdminConsole: true
  cluster:
    dataServiceMemoryQuota: 1024
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 30
  buckets:
    - name: AzResourceGroupBucket
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 3 
      name: all_services
      services:
        - data
        - index
        - query
        - search 
      dataPath: /opt/couchbase/var/lib/couchbase/data
      indexPath: /opt/couchbase/var/lib/couchbase/data
